export const Student = [
  {
    name: "Rahul Singh",
    studentid: 1105590,
    class: 11,
    rank:1,
    chapter: [
      
         "Stereo Chemistry",
         "Atomic structure",
         "States of matter",
         "Chemical Bonding",
         "Kinematics",
         "Newton Laws",
         "Quadratic Equation",
         "Seaquence and Series",
    ],
    level: 943,
    task: 8,
    progress: 7,
    asstask:"None"
  },
  {
    name: "Subham Banerjee",
    studentid: 1105591,
    class: 11,
    rank:2,
    chapter: [
      
     "Stereo Chemistry",
     "Atomic structure",
     "Nomenclature",
     "Kinematics",
     "Unit Dimension and measurement",
     "Quadratic Equation",
     "Complex Numbers",
      
    ],
    level: 802,
    task: 7,
    progress: 6,
    asstask:"1. Math Assignment"
  },
  {
    name: "Vikash Kumar",
    studentid: 1005592,
    rank:3,
    class: 10,
    chapter: [
      
         "Life Process",
       "Light Reflection and Refraction",
         "Chemical Reactions and Equations",
         "Forest and Wildlife",
         "Introduction to Trigonometry",
         "Co-ordinate Geometry",
      
    ],
    level: 700,
    task: 6,
    progress: 4,
  },
  {
    name: "Riya Singh",
    studentid: 1005593,
    rank:4,
    class: 10,
    chapter: [
      
         "Heredity",
         "Light Reflection and Refraction",
         "Electricity",
         "Metals and Non-Metals",
         "Carbon and Its Compound",
         "Real Numbers",
         "Polynomials",
         "Nationalism in India",
         "Power Sharing",
      
    ],
    level: 610,
    task: 10,
    progress: 7,
  },
  {
    name: "Ritesh Sharma",
    studentid: 1205594,
    class: 12,
    rank:5,
    chapter: [
    "Solid State", "Alkyl Halides and Aryl Halides", "Ray Optics", "Electrostatics", "Differential Calculus", "Functions",
    ],
    level: 636,
    task: 6,
    progress: 2,
  },
  {
    name: "Anurag Gupta",
    studentid: 1205595,
    class: 12,
    rank:6,
    chapter: [
       "Solutions",
       "Biomolecules",
       "P-Blocks",
       "Electrostatics",
       "Modern Physics",
       "Functions",
       "Inverse Trigonometric Functions",
  
    ],
    level: 505,
    task: 8,
    progress: 5,
  },
  {
    name: "Amrit Kashyap",
    studentid: 1205596,
    class: 12,
    rank:7,
    chapter: [
    
       "Solutions",
       "Alcohol, ether and Phenol",
       "Co-ordination Chemistry",
       "Current Electricity",
       "Magnetic Effect of current",
       "Vector",
       "3 Dimensional Geometry",
       "Probability",
    
    ],
    level: 499,
    task: 8,
    progress: 4,
  },
  {
    name: "Priyanshu Yadav",
    studentid: 1105597,
    class: 11,
    rank:8,
    chapter: [
  
       "Some basic concepts of chemistry",
       "Atomic structure",
       "States of matter",
       "Vector",
       "Kinematics",
       "Newton Laws of motion",
       "Centre of Mass",
       "Functions",
       "Complex Numbers",
       "Trigonometry",

    ],
    level: 389,
    task: 10,
    progress: 5,
  },
  {
    name: "Sweety Bhatt",
    studentid: 1205598,
    class: 12,
    rank:9,
    chapter: [
    
       "Solid State",
       "Solutions",
       "Current Electricity",
       "Electrostatics",
       "Matrices and Determinants",
       "Functions",
       "Linear Programming",
    
    ],
    level: 268,
    task: 7,
    progress: 2,
  },
  {
    name: "Md. Aslam",
    studentid: 1005599,
    class: 10,
    rank:10,
    chapter: [

       "Control and Co-ordination",
       "Light Reflection and Refraction",
       "Human Eye and Colourful World",
       "Metals and Non-Metals",
       "Source of Energy",
       "Our Environmrnt",
       "Arithmetic Progression",
       "Circles",
       "Area Related to Circles",
       "The Rise of Nationalism in Europe",
       "Water Resources",
       "Gender, Religion and Caste",
    ],
    level: 140,
    task: 12,
    progress: 2,
  },
];
